config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users do
    resources :runs
  end
end

# Prefix                   Verb   URI Pattern                             Controller#Action
# new_user_session         GET    /users/sign_in(.:format)                devise/sessions#new
# user_session             POST   /users/sign_in(.:format)                devise/sessions#create
# destroy_user_session     DELETE /users/sign_out(.:format)               devise/sessions#destroy
# user_password            POST   /users/password(.:format)               devise/passwords#create
# new_user_password        GET    /users/password/new(.:format)           devise/passwords#new
# edit_user_password       GET    /users/password/edit(.:format)          devise/passwords#edit
#                          PATCH  /users/password(.:format)               devise/passwords#update
#                          PUT    /users/password(.:format)               devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                 devise/registrations#cancel
# user_registration        POST   /users(.:format)                        devise/registrations#create
# new_user_registration    GET    /users/sign_up(.:format)                devise/registrations#new
# edit_user_registration   GET    /users/edit(.:format)                   devise/registrations#edit
#                          PATCH  /users(.:format)                        devise/registrations#update
#                          PUT    /users(.:format)                        devise/registrations#update
#                          DELETE /users(.:format)                        devise/registrations#destroy
#   root                   GET    /                                       users#index
# user_runs                GET    /users/:user_id/runs(.:format)          runs#index
#                          POST   /users/:user_id/runs(.:format)          runs#create
# new_user_run             GET    /users/:user_id/runs/new(.:format)      runs#new
# edit_user_run            GET    /users/:user_id/runs/:id/edit(.:format) runs#edit
# user_run                 GET    /users/:user_id/runs/:id(.:format)      runs#show
#                          PATCH  /users/:user_id/runs/:id(.:format)      runs#update
#                          PUT    /users/:user_id/runs/:id(.:format)      runs#update
#                          DELETE /users/:user_id/runs/:id(.:format)      runs#destroy

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :runs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
  end

  def show
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
    @runs = Run.where(user_id: params[:user_id])
    @mile_count = @runs.sum(:distance)
    @mile_count_ind = @runs.where(outdoors: false).sum(:distance)
    @mile_count_out = @runs.where(outdoors: true).sum(:distance)
    @long_run = @runs.maximum(:distance)
    @ind_runs = @runs.where(outdoors: false).count
    @out_runs = @runs.where(outdoors: true).count
    @long_run_ind = @runs.where(outdoors: false).maximum(:distance)
    @long_run_out = @runs.where(outdoors: true).maximum(:distance)
    @fast_pace = @runs.minimum(:pace).to_s.gsub(".",":")
    @fast_pace_mil = @runs.order(:pace).first
    @fast_pace_ind = @runs.where(outdoors: false).minimum(:pace).to_s.gsub(".",":")
    @fast_pace_out = @runs.where(outdoors: true).minimum(:pace).to_s.gsub(".",":")
    @fast_pace_ind_mil = @runs.where(outdoors: false).order(:pace).first
    @fast_pace_out_mil = @runs.where(outdoors: true).order(:pace).first
  end

  def new
    @user = User.find(params[:user_id])
    @run = Run.new
  end

  def show
  end

  def create
    @user = User.find(params[:user_id])
    @run = Run.new(run_params)

    if @run.save
      redirect_to user_runs_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def update
    if @run.update(run_params)
      redirect_to user_runs_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @run.destroy
    redirect_to user_runs_path(current_user.id)
  end

  private

  def set_run
    @run = Run.find(params[:id])
  end

  def run_params
    params.require(:run).permit(:run_date, :distance, :pace, :outdoors, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RunTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <p>
    <% if user_signed_in? %>
      <strong class='navbar-link'><%= current_user.email %></strong> |
      <%= link_to 'Home', users_url, :class => 'navbar-link' %> |
      <%= link_to 'Run Statistics', user_runs_path(current_user.id), :class => 'navbar-link' %> |
      <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
  </nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/runs/_form.html.erb
<%= form_for [@user, @run] do |form| %>
  <%= form.hidden_field :user_id, value: @user.id %>
  Date(yyyy-mm-dd): <%= form.text_field :run_date %><br/>
  Distance(miles): <%= form.text_field :distance %><br/>
  Pace(minutes/mile): <%= form.text_field :pace %><br/>
  Outdoors? <%= form.check_box :outdoors %><br/>
  <%= form.submit %>
<% end %>

app/views/runs/edit.html.erb
<h1>EDIT RUN</h1>

<div class="form-holder">
  <%= render :partial => 'form' %>
</div>

app/views/runs/index.html.erb
<h1>YOUR RUN STATS</h1>
<p class="new-run"><%= link_to 'Log New Run', new_user_run_path(@user.id), :class => 'navbar-link' %></p>
<h2>Last Three Runs</h2>
<% @runs.last(3).each do |run| %>
<div class="run-holder">
  <div class="indv-run">
    <h4>Date: <%= run.run_date %></h2>
    <% if run.outdoors %>
      <strong>Outdoors</strong><br/>
    <% else %>
      <strong>Indoors</strong><br/>
    <% end %>
    <strong>Distance: <%= run.distance %> miles</strong><br/>
    <strong>Pace: <%= run.pace.to_s.gsub(".",":") %> minutes per mile</strong><br/>
    <%= link_to 'Edit Run', edit_user_run_path(@user.id, run.id) %> -----
    <%= link_to 'Delete Run', user_run_path(@user.id, run.id), :method => 'delete' %>
  </div>
</div>
<% end %>
<h2>Other Stats</h2>
<div class="run-holder">
  <div class="stat-holder">
    <h2>Outdoors</h2>
    <strong>Number of Runs: <%= @out_runs %></strong> | <strong>Total Miles: <%= @mile_count_out %></strong><br/>
    <strong>Longest Run: <%= @long_run_out %> miles</strong><br/>
    <strong>Fastest Pace: <%= @fast_pace_out %> minutes per mile(<%= @fast_pace_out_mil.distance %> miles)</strong>
  </div>
</div>
<div class="run-holder">
  <div class="stat-holder">
    <h2>Indoors</h2>
    <strong>Number of Runs: <%= @ind_runs %></strong> | <strong>Total Miles: <%= @mile_count_ind %></strong><br/>
    <strong>Longest Run: <%= @long_run_ind %> miles</strong><br/>
    <strong>Fastest Pace: <%= @fast_pace_ind %> minutes per mile(<%= @fast_pace_ind_mil.distance %> miles)</strong>
  </div>
</div>
<div class="run-holder">
  <div class="stat-holder">
    <h2>Overall</h2>
    <strong>Number of Runs: <%= @runs.count %></strong> | <strong>Total Miles: <%= @mile_count %></strong><br/>
    <strong>Longest Run: <%= @long_run %> miles</strong><br/>
    <strong>Fastest Pace: <%= @fast_pace %> minutes per mile(<%= @fast_pace_mil.distance %> miles)</strong>
  </div>
</div>

app/views/runs/new.html.erb
<h1>NEW RUN</h1>

<div class="form-holder">
  <%= render :partial => 'form' %>
</div>

app/views/users/index.html.erb
<h1>Welcome to Run Tracker</h1>

app/views/users/show.html.erb
<h1>TEST SHOW</h1>